server:
  port: 18000


spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.100:3306/training?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: math
    password: math
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true


equation:
  addition:
    weight: 1
    addend-range: 10-99
    result-range: 20-99
    ensure-carry: true


  subtraction:
    weight: 1
    minuend-range: 10-99
    subtrahend-range: 10-99
    result-range: 10-99
    ensure-uncarry: true

  multiplication:
    weight: 0
    multiplier-range: 2-9
    result-range: 10-99

  division:
    weight: 0
    dividend-range: 10-99
    divisor-range: 2-9
    result-range: 2-50
    withExcept: true

question:
  blank-mode: 0 # 0-空白项在最后，1-空白项随机
  blank-slot-symbol: ____

quiz:
  source-template: static/excel/model-40.xlsx
  output-file: training.xlsx
  questions-per-sheet: 40
  begin-cells: B2,D2
  sheet-name-format: Page %d
  rows-per-column: 20
